### ISSUE TITLE
Determine focus range

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/Weeds3D-oak-d#13]
Determine what value in mm corresponds to the values 0-225 being used in the depthai library to set the focus

**Comment by priyajakhar** [comment]
From indoor testing, I got the below mentioned values:
0.5 m : 141-144
1.0 m : 135-138
1.5 m : 129-138

So overall we can keep the range between 129 and 145.

**Comment by priyajakhar** [comment]
Need to determine focus range for outdoor scene.
