### ISSUE TITLE
Develop script for image optimization

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/Weeds3D-oak-d#15]

**Comment by priyajakhar** [comment]
Not able to use Script node for this as it doesn't support numpy. Alternative is using a control queue, sending messages from host to the device.
Got a draft working version, needs revision.

**Comment by priyajakhar** [comment]
Scripts done and tested indoors. Need final revisions before testing out in the field.

**Comment by priyajakhar** [comment]
Latest updates working as expected, closing this issue.
