### ISSUE TITLE
Use various neural nets and report on camera performance

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/Weeds3D-oak-d#16]

**Comment by priyajakhar** [comment]
Out of the 3 nodes available: NN, MNDN and YDN, segmentation models use NN.

I tried a few detection models of varying size and a few segmentation models.

Segmentation models with input size 256x256 and 513x513 (more readily available for testing) had small memory footprints ~58 and 94 MiB usage (out of 340) respectively.
The bigger impact was seen on frame rate, it dropped from 25 to barely 5 FPS. Estimate for 700x700 model is of 2 FPS.

A bigger segmentation model with input size 960x720 had a much larger memory footprint (~248 MiB) and a significant drop in FPS (~0.5 ).
